
# Makefile generated by RSB v0.1.0

PROJECT = RSB
VERSION = 0.1.0


CFLAGS = -g -O0 -DDEBUG


.PHONY: all clean

all:
	@echo "Building $(PROJECT) v$(VERSION)"
	@echo "Flags: $(CFLAGS)"

	@echo "Logging enabled to build.log"


clean:
	@echo "Cleaning $(PROJECT)"
	rm -rf ./build