[processor.spellcheck]

[processor.make]
exclude_paths = ["Makefile"]

[processor.rumdl]
enabled = false

[processor.ascii_check]
enabled = false

[processor.mdl]
enabled = false

[processor.pandoc]
enabled = false

[processor.aspell]
enabled = false

[processor.markdownlint]
enabled = false

[processor.cargo]
enabled = false
