mod a2x;
mod cc;
mod drawio;
mod gem;
mod libreoffice;
mod marp;
mod markdown;
mod mermaid;
mod npm;
mod pandoc;
mod pdflatex;
mod pdfunite;
mod pip;
pub mod tags;
mod tera;

pub use a2x::A2xProcessor;
pub use cc::CcProcessor;
pub use drawio::DrawioProcessor;
pub use gem::GemProcessor;
pub use libreoffice::LibreofficeProcessor;
pub use marp::MarpProcessor;
pub use markdown::MarkdownProcessor;
pub use mermaid::MermaidProcessor;
pub use npm::NpmProcessor;
pub use pandoc::PandocProcessor;
pub use pdflatex::PdflatexProcessor;
pub use pdfunite::PdfuniteProcessor;
pub use pip::PipProcessor;
pub use tags::TagsProcessor;
pub use tera::TeraProcessor;
