[book]
authors = ["veltzer"]
language = "en"
src = "src"
title = "RSConstruct - Rust Build Tool"

[build]
build-dir = "book"

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/veltzer/rsconstruct"
edit-url-template = "https://github.com/veltzer/rsconstruct/edit/master/docs/{path}"
